### ISSUE TITLE
we want the same work with materialApp

### ISSUE THREAD

**Issue by bturkoglu** [googlecodelabs/flutter-cupertino-store#16]
Please, we want the same work with materialApp

**Comment by domesticmouse** [comment]
The `flutter-cupertino-store` was derived from the `shrine` sample that is the basis of the codelab series that starts with [MDC-101 Flutter: Material Components Basics](https://codelabs.developers.google.com/codelabs/mdc-101-flutter/index.html). I suspect that would be a good starting point for investigating how to build out a store application using Flutter and Material Components.
