### ISSUE TITLE
Dark Theme issue

### ISSUE THREAD

**Issue by Abhishek01039** [googlecodelabs/flutter-cupertino-store#28]
If the iPhone has a dark theme by default then it looks like this 
![image](https://user-images.githubusercontent.com/56479665/104995351-2cc42b00-5a4c-11eb-8e65-17c879dbc402.png)

**Suggestion:**
we have to add this line to make it work
```theme: const CupertinoThemeData(brightness: Brightness.light),```

After adding this line it looks like this 
![image](https://user-images.githubusercontent.com/56479665/104995474-5e3cf680-5a4c-11eb-89fe-8095c98804a8.png)

**Comment by Abhishek01039** [comment]
Also, I would like to work on it. @domesticmouse

**Comment by domesticmouse** [comment]
Sgtm, feel free to submit a PR. Thanks!

**Comment by domesticmouse** [comment]
Whups, please note this is a deprecated repo. Please see https://github.com/flutter/codelabs/tree/master/cupertino_store for the new repo location.

**Comment by domesticmouse** [comment]
Closing out this issue. Please feel free to re-file on the flutter/flutter issue tracker, and mention @domesticmouse in the bug.
